# Generated by Django 4.2.6 on 2023-10-14 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HelpInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Инфо",
                "verbose_name_plural": "Инфо",
            },
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Специализация",
                "verbose_name_plural": "Специализации",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=40, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=40, verbose_name="Имя")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="Отчество"
                    ),
                ),
                ("telegram_id", models.BigIntegerField(null=True, unique=True)),
                (
                    "telegram_username",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "is_doctor",
                    models.BooleanField(default=False, verbose_name="Доктор"),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.CreateModel(
            name="UserStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="Имя")),
                (
                    "telegram_username",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="Юзернейм"
                    ),
                ),
                ("telegram_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "select_specialization_step",
                    models.BooleanField(
                        default=False, verbose_name="Выбор специализации"
                    ),
                ),
                (
                    "select_doctor_step",
                    models.BooleanField(default=False, verbose_name="Выбор врача"),
                ),
                (
                    "select_date_step",
                    models.BooleanField(default=False, verbose_name="Выбор даты"),
                ),
                (
                    "select_time_step",
                    models.BooleanField(default=False, verbose_name="Выбор времени"),
                ),
                (
                    "user_info_step",
                    models.BooleanField(default=False, verbose_name="Ввод инфо"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата и время"
                    ),
                ),
                (
                    "is_notified",
                    models.BooleanField(default=False, verbose_name="Уведомление"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DoctorDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consultation_price",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Стоимость приема"
                    ),
                ),
                (
                    "about",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="doctors_photo",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_description",
                        to="supermedicapp.user",
                        verbose_name="Доктор",
                    ),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supermedicapp.specialization",
                        verbose_name="Специализация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Описание доктора",
                "verbose_name_plural": "Описания докторов",
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointment_time", models.DateTimeField(verbose_name="Дата и время")),
                (
                    "is_notified",
                    models.BooleanField(default=False, verbose_name="Уведомление"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Удалено"),
                ),
                (
                    "doctor_specialization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment",
                        to="supermedicapp.doctordescription",
                        verbose_name="Доктор и специализация",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_appointments",
                        to="supermedicapp.user",
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="Оплачено"),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Создано"),
                ),
                (
                    "link_sent",
                    models.BooleanField(default=False, verbose_name="Ссылка"),
                ),
                (
                    "is_notified",
                    models.BooleanField(default=False, verbose_name="Уведомление"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Удалено"),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supermedicapp.appointment",
                        verbose_name="Запись",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
    ]
