# Generated by Django 4.1.10 on 2023-11-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supermedicapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctordescription",
            name="medical_degree",
            field=models.TextField(
                blank=True, default=None, null=True, verbose_name="Мед. степень"
            ),
        ),
        migrations.AddField(
            model_name="doctordescription",
            name="work_experience",
            field=models.TextField(
                blank=True, default=None, null=True, verbose_name="Стаж работы"
            ),
        ),
        migrations.AddField(
            model_name="helpinfo",
            name="title",
            field=models.TextField(
                blank=True, default=None, null=True, verbose_name="Заголовок"
            ),
        ),
    ]
