# Generated by Django 4.1.10 on 2023-11-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supermedicapp", "0002_doctordescription_medical_degree_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstep",
            name="name",
            field=models.CharField(
                blank=True, default=None, max_length=40, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="userstep",
            name="telegram_id",
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="userstep",
            name="telegram_username",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=40,
                null=True,
                verbose_name="Юзернейм",
            ),
        ),
    ]
