# Generated by Django 4.1.10 on 2023-11-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "supermedicapp",
            "0003_alter_userstep_name_alter_userstep_telegram_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userstep",
            name="initial_step",
            field=models.BooleanField(default=True, verbose_name="Вход в бота"),
        ),
    ]
