version: "3.9"

services:
  web:
    build: .
    # при старте даём +x и запускаем наш скрипт
    entrypoint: ["/bin/sh", "-c", "chmod +x /app/entrypoint.sh && exec /app/entrypoint.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: supermedicdb
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpass

volumes:
  postgres_data:
