version: "3.9"

services:
  web:
    build: .
    volumes:
      - .:/app
      - ./static:/app/static
      - ./static/media:/app/static/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: supermedicdb
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpass

volumes:
  postgres_data:
