version: "3.9"

services:
  web:
    build: .
    volumes:
      - .:/app
      - ./static:/app/static
      - ./static/media:/app/static/media
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./static:/app/static
      - ./static/media:/app/static/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: supermedicdb
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpass

volumes:
  postgres_data:
